export { default as Header} from "./Header/Header"
export { default as Home} from "./Home/Home"
export { default as Hot} from "./Hot/Hot"
export { default as About} from "./About/About"
export { default as Arrivals} from "./Arrivals/Arrivals"
export { default as Contact} from "./Contact/Contact"
export { default as Footer} from "./Footer/Footer"
export {default as Products} from "./Products/Products"
